/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import UserInterface.JFrame.LoginJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rama
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel container;
    private Enterprise enterprise;
    private EcoSystem business;
    private DB4OUtil dB4OUtil;

    /**
     * Creates new form AdminWorkAreaJpanel
     */
    public AdminWorkAreaJPanel() {
        initComponents();
    }
    
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem business,DB4OUtil dB4OUtil) {
        initComponents();
        this.container = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        this.dB4OUtil = dB4OUtil;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        BACK2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();
        Forward = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(780, 580));
        setPreferredSize(new java.awt.Dimension(790, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valueLabel.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(254, 254, 254));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 150, 40));

        BACK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Close Window-26.png"))); // NOI18N
        BACK2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACK2MouseReleased(evt);
            }
        });
        add(BACK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Exit Sign-26.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        jLabel2.setBackground(new java.awt.Color(210, 214, 218));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administrator Work Area");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Businessman-26.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 30, 30));

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Manage Organization");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 180, 40));

        jLabel5.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Manage User");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 150, 40));

        jLabel6.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Gender Neutral User-26.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 30, 30));

        jLabel8.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Conference-26.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 150, 40));

        jLabel9.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Manage Employee");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 150, 40));

        jLabel7.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Enterprise");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, 40));

        BackGround.setFont(new java.awt.Font("URW Gothic L", 0, 9)); // NOI18N
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/background_4_800x600.png"))); // NOI18N
        BackGround.setBorder(null);
        BackGround.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BackGround.setOpaque(true);
        add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Next-26.png"))); // NOI18N
        Forward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(Forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 30));

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Previous-26.png"))); // NOI18N
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACK2MouseReleased

        System.exit(0);
    }//GEN-LAST:event_BACK2MouseReleased

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMousePressed

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased

        
         ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(container, enterprise);
        container.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased

         ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(container, enterprise);
        container.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(container, enterprise.getOrganizationDirectory());
        container.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased

         ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(container, enterprise.getOrganizationDirectory());
        container.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased

        ManageOrganisationJPanel manageOrganizationJPanel = new ManageOrganisationJPanel(container, enterprise.getOrganizationDirectory());
        container.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased

        ManageOrganisationJPanel manageOrganizationJPanel = new ManageOrganisationJPanel(container, enterprise.getOrganizationDirectory());
        container.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_jLabel4MouseReleased

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased

        container.removeAll();
        LoginJPanel lJP = new LoginJPanel(container, business, dB4OUtil);
        lJP.dB4OUtil.storeSystem(business);
        container.add("blank", lJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
//        lJP.dB4OUtil.storeSystem(business);
        
    }//GEN-LAST:event_exitMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel BACK2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Forward;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
