/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CatererRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Food.Food;
import Business.Food.FoodDirectory;
import Business.Money.Account;
import Business.Organization.CatererOrganization;
import Business.Organization.NurseOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.JFrame.LoginJPanel;
import UserInterface.SystemAdminWorkArea.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.DB4OUtil.DB4OUtil;

/**
 *
 * @author rama
 */
public class CatererWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel container;
    private CatererOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Account account;
    private FoodDirectory foodDirectory;
    private EcoSystem business;
    private DB4OUtil dB4OUtil;

    /**
     * Creates new form AdminWorkAreaJpanel
     */
    public CatererWorkAreaJPanel() {
        initComponents();
    }
    
     public CatererWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CatererOrganization organization, Enterprise enterprise, EcoSystem business,DB4OUtil dB4OUtil) {
    initComponents();

    this.container = userProcessContainer;
    this.organization = organization;
    this.enterprise = enterprise;
    this.userAccount = account;
    this.account = business.getAccount();
    this.foodDirectory = business.getFoodDirectory();
    this.business = business;
    this.dB4OUtil = dB4OUtil;
//    valueLabel.setText(enterprise.getName());
//        populateRequestTable();
    
    populateFoodJTable();
    }

    public void populateFoodJTable(){
         
        DefaultTableModel dtm = (DefaultTableModel) foodJTable.getModel();
        
        dtm.setRowCount(0);
        
        for(Food food : foodDirectory.getFoodDirectory()){
            Object[] row = new Object[2];
            row[0] = food.getName();
            row[1] = food.getCost();
            
            dtm.addRow(row);
        }
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACK2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        foodjTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodJTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        pricejTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();
        Forward = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 580));
        setPreferredSize(new java.awt.Dimension(790, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BACK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Close Window-26.png"))); // NOI18N
        BACK2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACK2MouseReleased(evt);
            }
        });
        add(BACK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Checkmark-26.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 30, 30));

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Exit Sign-26.png"))); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exit1MouseReleased(evt);
            }
        });
        add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        jLabel2.setBackground(new java.awt.Color(210, 214, 218));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Food ");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        foodjTextField.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        foodjTextField.setForeground(new java.awt.Color(1, 1, 1));
        foodjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        foodjTextField.setBorder(null);
        foodjTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        foodjTextField.setMinimumSize(new java.awt.Dimension(20, 17));
        foodjTextField.setOpaque(false);
        add(foodjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 200, 30));

        foodJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Item", "Price"
            }
        ));
        jScrollPane2.setViewportView(foodJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 380, 190));

        jLabel11.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Price");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 150, 40));

        pricejTextField.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        pricejTextField.setForeground(new java.awt.Color(1, 1, 1));
        pricejTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pricejTextField.setBorder(null);
        pricejTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pricejTextField.setMinimumSize(new java.awt.Dimension(20, 17));
        pricejTextField.setOpaque(false);
        add(pricejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 200, 30));

        jLabel13.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Name");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 150, 40));

        BackGround.setFont(new java.awt.Font("URW Gothic L", 0, 9)); // NOI18N
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/background_4_800x600.png"))); // NOI18N
        BackGround.setBorder(null);
        BackGround.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        BackGround.setOpaque(true);
        add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Next-26.png"))); // NOI18N
        Forward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(Forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 30));

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Previous-26.png"))); // NOI18N
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACK2MouseReleased

        System.exit(0);
    }//GEN-LAST:event_BACK2MouseReleased

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMousePressed

    private void exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MousePressed

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased

        try{
            
            if(foodjTextField.getText().isEmpty()||pricejTextField.getText().isEmpty()){
                throw new Exception();
            }
            
            String foodName = foodjTextField.getText();
            int foodCost = Integer.parseInt(pricejTextField.getText());
            
            if(foodCost<account.getFunds()){
                
             Food food = new Food();
             food.setName(foodName);
             food.setCost(foodCost);
             foodDirectory.setFoodDirectory(food);
             
             JOptionPane.showMessageDialog(null, "Food Item successfully added!");
             populateFoodJTable();
                
            }
            else{
             JOptionPane.showMessageDialog(null, "Insufficient funds in account. Raise Donation!");
            }
            
             
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Enter fields Correctly!");
        }
        
       
    }//GEN-LAST:event_exitMouseReleased

    private void exit1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseReleased

        container.removeAll();
        LoginJPanel lJP = new LoginJPanel(container, business, dB4OUtil);
         lJP.dB4OUtil.storeSystem(business);
        container.add("blank", lJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
//        lJP.dB4OUtil.storeSystem(business);
//        dB4OUtil.storeSystem(system);
        
    }//GEN-LAST:event_exit1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel BACK2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Forward;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JTable foodJTable;
    private javax.swing.JTextField foodjTextField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pricejTextField;
    // End of variables declaration//GEN-END:variables
}
