/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.JFrame;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.DonorRole.*;
import UserInterface.CatererRole.*;
import UserInterface.SystemAdminWorkArea.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rama
 */
public class LoginJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel container;
    public DB4OUtil dB4OUtil;
    /**
     * Creates new form AdminWorkAreaJpanel
     */
   

    public LoginJPanel(JPanel container1,EcoSystem system1, DB4OUtil dB4OUtil) {
        initComponents();
        //system = system1;
        container = container1;
        system = system1;
        this.dB4OUtil = dB4OUtil;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACK2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        enter1 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();
        Forward = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 580));
        setPreferredSize(new java.awt.Dimension(790, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BACK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Close Window-26.png"))); // NOI18N
        BACK2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACK2MouseReleased(evt);
            }
        });
        add(BACK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel2.setBackground(new java.awt.Color(210, 214, 218));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Log-In");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jLabel5.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("User Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 150, 40));

        userNameJTextField.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        userNameJTextField.setForeground(new java.awt.Color(1, 1, 1));
        userNameJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameJTextField.setBorder(null);
        userNameJTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userNameJTextField.setMinimumSize(new java.awt.Dimension(20, 17));
        userNameJTextField.setOpaque(false);
        add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 250, 30));

        jLabel7.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Password");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, 40));

        passwordField.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setMinimumSize(new java.awt.Dimension(20, 17));
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 250, 30));

        enter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/JFrame/Enter-26.png"))); // NOI18N
        enter1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                enter1MouseReleased(evt);
            }
        });
        add(enter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        BackGround.setFont(new java.awt.Font("URW Gothic L", 0, 9)); // NOI18N
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/background_4_800x600.png"))); // NOI18N
        BackGround.setBorder(null);
        BackGround.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        BackGround.setOpaque(true);
        add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Next-26.png"))); // NOI18N
        Forward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(Forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 30));

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Previous-26.png"))); // NOI18N
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Exit Sign-26.png"))); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit1MousePressed(evt);
            }
        });
        add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACK2MouseReleased

        System.exit(0);
    }//GEN-LAST:event_BACK2MouseReleased

    private void exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MousePressed

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void enter1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1MouseReleased
   
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        
        if (userAccount == null) {
            //Step2: Go inside each network to check each enterprise
            for (Network network : system.getNetworkList()) {
                //Step 2-a: Check against each enterprise
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if (userAccount == null) {
                        //Step3: Check against each organization inside that enterprise
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                inEnterprise = enterprise;
                                inOrganization = organization;
                                break;
                            }
                        }
                    } else {
                        inEnterprise = enterprise;
                        break;
                      }
                    if (inOrganization != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }
        }
        
         if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid Credentails!");
            return;
        } else {
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system, dB4OUtil));
            layout.next(container);
        }
        
    }//GEN-LAST:event_enter1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel BACK2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Forward;
    private javax.swing.JLabel enter1;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
