/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rama
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {
    private final JPanel container;
    private final EcoSystem system;

    /**
     * Creates new form AdminWorkAreaJpanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.container = userProcessContainer;
        this.system = system;

        populateNetworkTable();
    }

    
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACK = new javax.swing.JLabel();
        BACK2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        BackGround = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        Forward = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 580));
        setPreferredSize(new java.awt.Dimension(790, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Previous-26.png"))); // NOI18N
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACKMouseReleased(evt);
            }
        });
        add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        BACK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Close Window-26.png"))); // NOI18N
        BACK2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACK2MouseReleased(evt);
            }
        });
        add(BACK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Checkmark-26.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 30, 30));

        jLabel2.setBackground(new java.awt.Color(210, 214, 218));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Network");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jLabel10.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 150, 40));

        nameJTextField.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(1, 1, 1));
        nameJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameJTextField.setBorder(null);
        nameJTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameJTextField.setMinimumSize(new java.awt.Dimension(20, 17));
        nameJTextField.setOpaque(false);
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 200, 30));

        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        networkJTable.setEnabled(false);
        jScrollPane2.setViewportView(networkJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 380, 190));

        BackGround.setFont(new java.awt.Font("URW Gothic L", 0, 9)); // NOI18N
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/background_4_800x600.png"))); // NOI18N
        BackGround.setBorder(null);
        BackGround.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BackGround.setOpaque(true);
        add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Exit Sign-26.png"))); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit1MousePressed(evt);
            }
        });
        add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Next-26.png"))); // NOI18N
        Forward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(Forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACK2MouseReleased

        System.exit(0);
    }//GEN-LAST:event_BACK2MouseReleased

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMousePressed

    private void exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MousePressed

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased

        try{
            if(nameJTextField.getText().isEmpty()){
               throw new Exception();
            }
            else{
                    String name = nameJTextField.getText();
                    Network network = system.createAndAddNetwork();
                    network.setName(name);
                    populateNetworkTable();
            }
        }
        
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null," Give a name to your new network! ");
        }
        
        
        
    }//GEN-LAST:event_exitMouseReleased

    private void BACKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseReleased

        container.remove(this);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
    }//GEN-LAST:event_BACKMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel BACK2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Forward;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTable networkJTable;
    // End of variables declaration//GEN-END:variables
}
