/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rama
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {
    private final JPanel container;
    private final EcoSystem system;

    /**
     * Creates new form AdminWorkAreaJpanel
     */
       
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.container = userProcessContainer;
        this.system = system;

        populateTable();
        populateNetworkComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }
    
    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseJComboBox.addItem(enterprise);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        BACK2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        enterpriseJComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        passwordJPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameJTextField1 = new javax.swing.JTextField();
        BackGround = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        Forward = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 580));
        setPreferredSize(new java.awt.Dimension(790, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 150, 40));

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Previous-26.png"))); // NOI18N
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACKMouseReleased(evt);
            }
        });
        add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        BACK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Close Window-26.png"))); // NOI18N
        BACK2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACK2MouseReleased(evt);
            }
        });
        add(BACK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Checkmark-26.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 30, 30));

        jLabel2.setBackground(new java.awt.Color(210, 214, 218));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Enterprise Accounts");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jLabel7.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Enterprise");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 40));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, -1));

        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseJComboBox.setBorder(null);
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, -1));

        jLabel10.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("User Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 150, 40));

        nameJTextField.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(1, 1, 1));
        nameJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameJTextField.setBorder(null);
        nameJTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameJTextField.setMinimumSize(new java.awt.Dimension(20, 17));
        nameJTextField.setOpaque(false);
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 210, 30));

        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "UserName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseJTable.setEnabled(false);
        jScrollPane2.setViewportView(enterpriseJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 710, 180));

        passwordJPasswordField.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        passwordJPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordJPasswordField.setMinimumSize(new java.awt.Dimension(20, 17));
        passwordJPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordJPasswordFieldKeyReleased(evt);
            }
        });
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 210, 30));

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 150, 40));

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 150, 40));

        usernameJTextField1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        usernameJTextField1.setForeground(new java.awt.Color(1, 1, 1));
        usernameJTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameJTextField1.setBorder(null);
        usernameJTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameJTextField1.setMinimumSize(new java.awt.Dimension(20, 17));
        usernameJTextField1.setOpaque(false);
        add(usernameJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 210, 30));

        BackGround.setFont(new java.awt.Font("URW Gothic L", 0, 9)); // NOI18N
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/background_4_800x600.png"))); // NOI18N
        BackGround.setBorder(null);
        BackGround.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BackGround.setOpaque(true);
        add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Exit Sign-26.png"))); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit1MousePressed(evt);
            }
        });
        add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Next-26.png"))); // NOI18N
        Forward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(Forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACK2MouseReleased

        System.exit(0);
    }//GEN-LAST:event_BACK2MouseReleased

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMousePressed

    private void exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MousePressed

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed

    private void passwordJPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJPasswordFieldKeyReleased

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
        
        
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased

          try{
                 if(nameJTextField.getText().isEmpty()||usernameJTextField1.getText().isEmpty()){
                    throw new Exception();
                 }
                 
                 else{
                        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

                        String username = usernameJTextField1.getText();
                        String password = String.valueOf(passwordJPasswordField.getPassword());
                        String name = nameJTextField.getText();

                        Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);

                        UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
                        populateTable();
                 }
        }
        
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null," Please Enter fields first ");
        }
        
        
        
        
        
        
       
        
    }//GEN-LAST:event_exitMouseReleased

    private void BACKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseReleased

         container.remove(this);
         
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
    }//GEN-LAST:event_BACKMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel BACK2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Forward;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JTextField usernameJTextField1;
    // End of variables declaration//GEN-END:variables
}
