/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Food.Food;
import Business.Food.FoodDirectory;
import Business.Organization.DoctorOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rama
 */
public class DoctorInstructionJPanel extends javax.swing.JPanel {
    private final JPanel container;
    private final Patient patient;
    private final UserAccount userAccount;
    private final DoctorOrganization organization;
    private final Food food;
    private final EcoSystem business;
    private final Enterprise enterprise;
    private final WorkQueue workQueue;
    private final DB4OUtil dB4OUtil;

    /**
     * Creates new form AdminWorkAreaJpanel
     */

    public DoctorInstructionJPanel(JPanel container, Patient patient, UserAccount userAccount, DoctorOrganization organization, Enterprise enterprise,Food food, EcoSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        
        this.container = container;
        this.patient = patient;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.food = food;
        this.business = system;
        this.workQueue = business.getWorkQueue();
        this.dB4OUtil = dB4OUtil;
        
        enterpriseJLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Forward = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        BACK2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseJLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 580));
        setPreferredSize(new java.awt.Dimension(790, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Enterprise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, 40));

        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Checkmark-26.png"))); // NOI18N
        Forward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ForwardMouseReleased(evt);
            }
        });
        add(Forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 30));

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Previous-26.png"))); // NOI18N
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACKMouseReleased(evt);
            }
        });
        add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        BACK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Close Window-26.png"))); // NOI18N
        BACK2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACK2MouseReleased(evt);
            }
        });
        add(BACK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel2.setBackground(new java.awt.Color(210, 214, 218));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Instruction to Nurse");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        enterpriseJLabel.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        enterpriseJLabel.setForeground(new java.awt.Color(254, 254, 254));
        enterpriseJLabel.setText("<value>");
        add(enterpriseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 150, 40));

        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(1, 1, 1));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setMinimumSize(new java.awt.Dimension(20, 17));
        jTextField2.setOpaque(false);
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 250, 80));

        jLabel11.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Doctor's Instruction");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, 40));

        BackGround.setFont(new java.awt.Font("URW Gothic L", 0, 9)); // NOI18N
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/background_4_800x600.png"))); // NOI18N
        BackGround.setBorder(null);
        BackGround.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        BackGround.setOpaque(true);
        add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Exit Sign-26.png"))); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit1MousePressed(evt);
            }
        });
        add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACK2MouseReleased

        System.exit(0);
    }//GEN-LAST:event_BACK2MouseReleased

    private void exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MousePressed

    private void ForwardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForwardMouseReleased

        
        try{
                 if(jTextField2.getText().isEmpty()){
                    throw new Exception();
                 }
                 
                 else{
                         //workrequest generation here;
                        String doctorInstruction = jTextField2.getText();

                        WorkRequest workRequest = new WorkRequest();
                        workRequest.setPatient(patient);
                        workRequest.setSender(userAccount);
                        workRequest.setFood(food);
                        workRequest.setInstruction(doctorInstruction);

                        workQueue.setWorkQueue(workRequest);

                        JOptionPane.showMessageDialog(null, "WorkRequest successfully created!");

                        DoctorWorkAreaJPanel dwap = new DoctorWorkAreaJPanel(container, userAccount, organization, enterprise, business, dB4OUtil);
                        container.add(dwap);
                        CardLayout layout = (CardLayout) container.getLayout();
                        layout.next(container);
                 }
        }
        
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null," Enter an Instruction to be followed! ");
        }
      
    }//GEN-LAST:event_ForwardMouseReleased

    private void BACKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseReleased

        //code to go back here
        container.remove(this);
         
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
    }//GEN-LAST:event_BACKMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel BACK2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Forward;
    private javax.swing.JLabel enterpriseJLabel;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
