/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Food.FoodDirectory;
import Business.Organization.DoctorOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rama
 */
public class PatientHistoryJPanel extends javax.swing.JPanel {
    private JPanel container;
    private Patient patient;
    private FoodDirectory foodDirectory;
    private WorkQueue workQueue;
    private UserAccount userAccount;
    private DoctorOrganization organization;
    private EcoSystem system;
    private final Enterprise enterprise;
    private final DB4OUtil dB4OUtil;
    /**
     * Creates new form AdminWorkAreaJpanel
     */
   
    
    public PatientHistoryJPanel(JPanel container,Patient patient,UserAccount userAccount,DoctorOrganization organization,Enterprise  enterprise,FoodDirectory  foodDirectory, EcoSystem system, DB4OUtil dB4OUtil){
        
        initComponents();
    
        this. container = container;
        this. patient = patient;
        this.enterprise = enterprise;
        this. userAccount = userAccount;
        this. foodDirectory = foodDirectory;
        this. dB4OUtil = dB4OUtil;
        
        this. workQueue = system.getWorkQueue();
        this. system = system;
        
        populateHistoryJTable();
        enterpriseJLabel.setText(enterprise.getName());
    }
    
    public void populateHistoryJTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) historyJTable.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest workRequest : workQueue.getWorkQueue()){
            
            if(workRequest.getPatient().getName().equalsIgnoreCase(patient.getName())){
                Object[] row = new Object[3];
                
                row[0] = workRequest.getFood().getName();
                row[1] = workRequest.getInstruction();
                row[2] = workRequest.getFeedback();
                
                dtm.addRow(row);
                 
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Forward = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        BACK2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 580));
        setPreferredSize(new java.awt.Dimension(790, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Prescribe New");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 160, 50));

        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Next-26.png"))); // NOI18N
        Forward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ForwardMouseReleased(evt);
            }
        });
        add(Forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, 30));

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Previous-26.png"))); // NOI18N
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACKMouseReleased(evt);
            }
        });
        add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        BACK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Close Window-26.png"))); // NOI18N
        BACK2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BACK2MouseReleased(evt);
            }
        });
        add(BACK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel2.setBackground(new java.awt.Color(210, 214, 218));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Patient Food History");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        enterpriseJLabel.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        enterpriseJLabel.setForeground(new java.awt.Color(254, 254, 254));
        enterpriseJLabel.setText("<value>");
        add(enterpriseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 150, 40));

        historyJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food", "Doctor Instruction", "Service Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        historyJTable.setEnabled(false);
        jScrollPane2.setViewportView(historyJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 420, 200));

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Enterprise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, 40));

        BackGround.setFont(new java.awt.Font("URW Gothic L", 0, 9)); // NOI18N
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/background_4_800x600.png"))); // NOI18N
        BackGround.setBorder(null);
        BackGround.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        BackGround.setOpaque(true);
        add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Exit Sign-26.png"))); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit1MousePressed(evt);
            }
        });
        add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Basic/Refresh-26.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACK2MouseReleased

        System.exit(0);
    }//GEN-LAST:event_BACK2MouseReleased

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMousePressed

    private void exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MousePressed

    private void ForwardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForwardMouseReleased

//         DefaultTableModel dtm = (DefaultTableModel) historyJTable.getModel();
//         int selectedRow = historyJTable.getSelectedRow();
//         dtm.getValueAt(selectedRow, 0);
        
        AssignFoodJPanel afjp = new AssignFoodJPanel(container, patient, userAccount, organization, enterprise, foodDirectory, system, dB4OUtil);
        container.add(afjp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
        
    }//GEN-LAST:event_ForwardMouseReleased

    private void BACKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseReleased
      
        container.remove(this);
         
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
    }//GEN-LAST:event_BACKMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel BACK2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Forward;
    private javax.swing.JLabel enterpriseJLabel;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JTable historyJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
